### ISSUE TITLE
Query to retrieve all referenced papers

### ISSUE THREAD

**Issue by kuzeko** [dice-group/COVID19DS#1]
Hello,

I am trying to use this dataset but I am confused about a very simple query.
How can I retrieve given a paper (e.g., `https://covid-19ds.data.dice-research.org/resource/pmc1065257` )
al the other papers that it references and are also inside this dataset?

Thanks

**Comment by MSherif** [comment]
Here you are:

```
PREFIX cvdr: <https://covid-19ds.data.dice-research.org/resource/> 
PREFIX cvdo: <https://covid-19ds.data.dice-research.org/ontology/> 
PREFIX bibtex: <http://purl.org/net/nknouf/ns/bibtex#> 
PREFIX nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
PREFIX its: <http://www.w3.org/2005/11/its/rdf#>

SELECT DISTINCT ?bibEntry WHERE {
cvdr:pmc1065257 cvdo:hasBody ?body .
?body cvdo:hasSection ?section .
?refCont nif:referenceContext ?section .
?refCont its:taIdentRef ?bibEntry .
?bibEntry a bibtex:Entry .
}
```

**Comment by kuzeko** [comment]
Perfect, thanks!

**Comment by kuzeko** [comment]
Hi @MSherif  I've tried your query and I think  it misses a piece, below is my modified query. 
Note the Same As to the scolarly article, so if I am correct, this will allow to proceed BFS across the citation network.
Is this wrong?

```

SELECT DISTINCT ?paper1 ?paper2   WHERE {

VALUES ?paper1 { <https://covid-19ds.data.dice-research.org/resource/pmc1065257> }

?paper1 cvdo:hasBody ?body .
?body cvdo:hasSection ?section .
?refCont nif:referenceContext ?section .
?refCont its:taIdentRef ?entry .
?entry a bibtex:Entry .
?entry <http://www.w3.org/2011/http#//www.w3.org/2002/07/owl#sameAs> ?paper2 .
?paper2 a  <http://schema.org/ScholarlyArticle> .

}

```

**Comment by kuzeko** [comment]
Hi @MSherif  I've tried your query and I think  it misses a piece, below is my modified query. 
Note the Same As to the scolarly article, so if I am correct, this will allow to proceed BFS across the citation network.
Is this wrong?

```

SELECT DISTINCT ?paper1 ?paper2   WHERE {

VALUES ?paper1 { <https://covid-19ds.data.dice-research.org/resource/pmc1065257> }

?paper1 cvdo:hasBody ?body .
?body cvdo:hasSection ?section .
?refCont nif:referenceContext ?section .
?refCont its:taIdentRef ?entry .
?entry a bibtex:Entry .
?entry <http://www.w3.org/2011/http#//www.w3.org/2002/07/owl#sameAs> ?paper2 .
?paper2 a  <http://schema.org/ScholarlyArticle> .

}

```

**Comment by aalexandrasilva** [comment]
Hi @kuzeko,
I would say, the query @MSherif shared is more correct to obtain the referenced papers.
> 
> ```
> PREFIX cvdr: <https://covid-19ds.data.dice-research.org/resource/> 
> PREFIX cvdo: <https://covid-19ds.data.dice-research.org/ontology/> 
> PREFIX bibtex: <http://purl.org/net/nknouf/ns/bibtex#> 
> PREFIX nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
> PREFIX its: <http://www.w3.org/2005/11/its/rdf#>
> 
> SELECT DISTINCT ?bibEntry WHERE {
> cvdr:pmc1065257 cvdo:hasBody ?body .
> ?body cvdo:hasSection ?section .
> ?refCont nif:referenceContext ?section .
> ?refCont its:taIdentRef ?bibEntry .
> ?bibEntry a bibtex:Entry .
> }
> ```
> 
> [Show result](https://covid-19ds.data.dice-research.org/sparql?default-graph-uri=&query=PREFIX+cvdr%3A+%3Chttps%3A%2F%2Fcovid-19ds.data.dice-research.org%2Fresource%2F%3E+%0D%0APREFIX+cvdo%3A+%3Chttps%3A%2F%2Fcovid-19ds.data.dice-research.org%2Fontology%2F%3E+%0D%0APREFIX+bibtex%3A+%3Chttp%3A%2F%2Fpurl.org%2Fnet%2Fnknouf%2Fns%2Fbibtex%23%3E+%0D%0APREFIX+nif%3A+%3Chttp%3A%2F%2Fpersistence.uni-leipzig.org%2Fnlp2rdf%2Fontologies%2Fnif-core%23%3E%0D%0APREFIX+its%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2005%2F11%2Fits%2Frdf%23%3E%0D%0A%0D%0ASELECT+DISTINCT+%3FbibEntry+WHERE+%7B%0D%0Acvdr%3Apmc1065257+cvdo%3AhasBody+%3Fbody+.%0D%0A%3Fbody+cvdo%3AhasSection+%3Fsection+.%0D%0A%3FrefCont+nif%3AreferenceContext+%3Fsection+.%0D%0A%3FrefCont+its%3AtaIdentRef+%3FbibEntry+.%0D%0A%3FbibEntry+a+bibtex%3AEntry+.%0D%0A%7D%0D%0A%0D%0A&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)

If you execute this query with the paper [cvdr:pmc1065257](https://covid-19ds.data.dice-research.org/resource/pmc1065257)  as an example, you'll see that none of the references are linked to other resources in the dataset. With your query, you'll miss out on the references unless explicitly linked with an `owl:sameAs` predicate.

**Comment by kuzeko** [comment]
Hi Alexandra, thanks for the reply, but in my question  I explicitly need 

>  al the other papers that it references and **are also inside this dataset**

So if they do not have the sameAs are not inside the dataset but are external to it, right?

**Comment by MSherif** [comment]
Hi Kuzeko,
as we do not have `owl:sameAs` links between bib-entries and papers. One work around would be to catch the papers by titles using the following queries
```
PREFIX cvdr: <https://covid-19ds.data.dice-research.org/resource/> 
PREFIX cvdo: <https://covid-19ds.data.dice-research.org/ontology/> 
PREFIX bibtex: <http://purl.org/net/nknouf/ns/bibtex#> 
PREFIX nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
PREFIX its: <http://www.w3.org/2005/11/its/rdf#>
PREFIX schema: <http://schema.org/> 
PREFIX dcterms: <http://purl.org/dc/terms/> 

SELECT DISTINCT ?paper ?bibTitle ?refPaper   WHERE {

VALUES ?paper { <https://covid-19ds.data.dice-research.org/resource/pmc1065257> }

?paper cvdo:hasBody ?body .
?body cvdo:hasSection ?section .
?refCont nif:referenceContext ?section .
?refCont its:taIdentRef ?entry .
?entry a bibtex:Entry .
?entry bibtex:hasTitle ?bibTitle .

?refPaper a  schema:ScholarlyArticle ;
          dcterms:title ?bibTitle .
}
```
Still linking bib-entries with paper is a good idea. Using the `owl:sameAs` for such a link is semantically suboptimal as bib-entries is not papers. We would conceder linking them in our next version of the KG.

**Comment by kuzeko** [comment]
hi @MSherif  
I am confused, I found a file containing those `sameAs` did I misunderstood what they are?
Are you saying that at the time I cannot extract a full induced citation network within this dataset?

Thanks

**Comment by MSherif** [comment]
You are absolutely correct, I totally forgot that we already did this.

**Comment by kuzeko** [comment]
Thanks @MSherif  so my query is the correct one then?

**Comment by MSherif** [comment]
yes
