### ISSUE TITLE
Corrupt URI inside `bibEntries_hasPublication.nt`

### ISSUE THREAD

**Issue by kuzeko** [dice-group/COVID19DS#2]
Hello,

I've downloaded the data dump from https://hobbitdata.informatik.uni-leipzig.de/COVID19DS/archive

and the file `bibEntries_hasPublication.nt`
contains triples of the form:

```
<https://covid-19ds.data.dice-research.org/resource/pmc7250281_B20_1> <http://www.w3.org/2011/http#//www.w3.org/2002/07/owl#sameAs> <https://covid-19ds.data.dice-research.org/resource/pmc7092802> .
```

I believe the predicate `<http://www.w3.org/2011/http#//www.w3.org/2002/07/owl#sameAs>` is not correct and should be just

`<http#//www.w3.org/2002/07/owl#sameAs>`

isn't it?

**Comment by MSherif** [comment]
Yes it is. We will fix this in the next version of the KG by next week.

**Comment by kuzeko** [comment]
Thanks, Will the old files be updated as well?

**Comment by aalexandrasilva** [comment]
@kuzeko Thanks for using our dataset and pointing out this issue. 👍 
We've fixed the files that have the faulty `owl:sameAs` URIs, including the older archive files.
