### ISSUE TITLE
Query to retrieve named entities from a paper

### ISSUE THREAD

**Issue by kuzeko** [dice-group/COVID19DS#3]
Hello,  @MSherif 

 I am trying to get a query to extract all named entities mapped within a paper.
So far I'm failing.

This is the query I tried

```
SELECT *
WHERE {

?paper1 cvdo:hasBody ?body .
?body cvdo:hasSection ?section .
?refCont nif:referenceContext ?section .
?refCont nif:anchorOf ?entityRef .
?refCont its:taIdentRef  ?entity .

} 
```

So I tried at least to get all named entities in the database, and I am also failing.

The following query is supposed to give me at least entities containing the string acid, as per  Listing 7 in the paper.
But it returns an empty set. 

```
SELECT DISTINCT ?entity
WHERE {

?s ?p ?entity . FILTER(regex(?entity, "acid" ))

} LIMIT 100
```

Neither of these queries return to me the "folic acid" string in your paper.

Overall, it would be nice if this repo was accompanied by competency questions and how to translate them into SPARQL.
Thanks

**Comment by MSherif** [comment]
The example in the paper works fine, you just need to add the prefixes before the `SELECT` statement. An even way to answer your query is via the following queries:

- All named entities in all papers 
```
PREFIX cvdo: <https://covid-19ds.data.dice-research.org/ontology/>
PREFIX nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> 

SELECT DISTINCT ?paper ?section ?entity ?ne WHERE {
       ?entity a nif:Context ;
               nif:anchorOf ?ne .
       ?entity nif:referenceContext ?section .
       ?body cvdo:hasSection ?section .
       ?paper cvdo:hasBody ?body .
}
```
[Results](https://covid-19ds.data.dice-research.org/sparql?default-graph-uri=&query=PREFIX+cvdo%3A+%3Chttps%3A%2F%2Fcovid-19ds.data.dice-research.org%2Fontology%2F%3E%0D%0APREFIX+nif%3A+%3Chttp%3A%2F%2Fpersistence.uni-leipzig.org%2Fnlp2rdf%2Fontologies%2Fnif-core%23%3E+%0D%0A%0D%0A%0D%0ASELECT+DISTINCT+%3Fpaper+%3Fsection+%3Fentity+%3Fne+WHERE+%7B%0D%0A+++++++%3Fentity+a+nif%3AContext+%3B%0D%0A+++++++++++++++nif%3AanchorOf+%3Fne+.%0D%0A+++++++%3Fentity+nif%3AreferenceContext+%3Fsection+.%0D%0A+++++++%3Fbody+cvdo%3AhasSection+%3Fsection+.%0D%0A+++++++%3Fpaper+cvdo%3AhasBody+%3Fbody+.%0D%0A%7D%0D%0A%0D%0A&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)

- All papers with associated sections that mention `folic acid`
```
PREFIX cvdo: <https://covid-19ds.data.dice-research.org/ontology/>
PREFIX nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> 

SELECT DISTINCT ?paper ?section WHERE {
       ?entity a nif:Context ;
               nif:anchorOf "folic acid";
               nif:referenceContext ?section .
       ?body cvdo:hasSection ?section .
       ?paper cvdo:hasBody ?body .
}
```
[Result](https://covid-19ds.data.dice-research.org/sparql?default-graph-uri=&query=PREFIX+cvdo%3A+%3Chttps%3A%2F%2Fcovid-19ds.data.dice-research.org%2Fontology%2F%3E%0D%0APREFIX+nif%3A+%3Chttp%3A%2F%2Fpersistence.uni-leipzig.org%2Fnlp2rdf%2Fontologies%2Fnif-core%23%3E+%0D%0A%0D%0A%0D%0ASELECT+DISTINCT+%3Fpaper+%3Fsection+WHERE+%7B%0D%0A+++++++%3Fentity+a+nif%3AContext+%3B%0D%0A+++++++++++++++nif%3AanchorOf+%22folic+acid%22%3B%0D%0A+++++++++++++++nif%3AreferenceContext+%3Fsection+.%0D%0A+++++++%3Fbody+cvdo%3AhasSection+%3Fsection+.%0D%0A+++++++%3Fpaper+cvdo%3AhasBody+%3Fbody+.%0D%0A%7D%0D%0A%0D%0A&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)

- Distict nemed entities in a specific paper (i.e., `cvdr:pmc8387096`)
```
PREFIX cvdo: <https://covid-19ds.data.dice-research.org/ontology/>
PREFIX nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> 
prefix cvdr: <https://covid-19ds.data.dice-research.org/resource/> 


SELECT DISTINCT ?ne WHERE {
   ?entity a nif:Context ;
           nif:anchorOf ?ne .
       ?body cvdo:hasSection ?section .
       cvdr:pmc8387096 cvdo:hasBody ?body .
}
```
[Results](https://covid-19ds.data.dice-research.org/sparql?default-graph-uri=&query=PREFIX+cvdo%3A+%3Chttps%3A%2F%2Fcovid-19ds.data.dice-research.org%2Fontology%2F%3E%0D%0APREFIX+nif%3A+%3Chttp%3A%2F%2Fpersistence.uni-leipzig.org%2Fnlp2rdf%2Fontologies%2Fnif-core%23%3E+%0D%0Aprefix+cvdr%3A+%3Chttps%3A%2F%2Fcovid-19ds.data.dice-research.org%2Fresource%2F%3E+%0D%0A%0D%0A%0D%0ASELECT+DISTINCT+%3Fne+WHERE+%7B%0D%0A+++%3Fentity+a+nif%3AContext+%3B%0D%0A+++++++++++nif%3AanchorOf+%3Fne+.%0D%0A+++++++%3Fbody+cvdo%3AhasSection+%3Fsection+.%0D%0A+++++++cvdr%3Apmc8387096+cvdo%3AhasBody+%3Fbody+.%0D%0A%7D%0D%0A%0D%0A&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)
